### PR TITLE
Get connection settings from approval controller.

### PR DESCRIPTION
**Pull request by GoebelL**
**Changes in this Pull Request:**
- Minor changes

***IMPORTANT:*** https://github.com/servicecatalog/oscm-app/pull/96 has to be merged first!

**Mandatory checks:**
- [X] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [ ] Changes were tested manually
- [x] Java code changes are unit tested

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
- Build reference (e.g. tag on dockerhub)

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-approval/41)

### CODE REVIEW

**Review by kowalczyka — CHANGES_REQUESTED** [review]
> Reviewed 10 of 14 files at r1, 3 of 3 files at r2, 1 of 3 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-approval/41)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @GoebelL and @kowalczyka)

___
*[approval-impl/package.launch, line 1 at r2](https://reviewable.io/reviews/servicecatalog/oscm-approval/41#-MJ7NA299MzjldfFJSO1:-MJ7NA299MzjldfFJSO2:b-f3ntb1) ([raw file](https://github.com/servicecatalog/oscm-approval/blob/7b8f92d267d762200dddeab234f298f3ea3979b9/approval-impl/package.launch#L1)):*
> ```XML
> <?xml version="1.0" encoding="UTF-8" standalone="no"?>
> ```

Is this file necessary?

**Review by GoebelL — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-approval/41)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @kowalczyka)

___
*[approval-impl/package.launch, line 1 at r2](https://reviewable.io/reviews/servicecatalog/oscm-approval/41#-MJ7NA299MzjldfFJSO1:-MJ7TqSeDMdhpf2ZTCMu:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-approval/blob/7b8f92d267d762200dddeab234f298f3ea3979b9/approval-impl/package.launch#L1)):*
<details><summary><i>Previously, kowalczyka (Arkadiusz Kowalczyk) wrote…</i></summary><blockquote>

Is this file necessary?
</blockquote></details>

Done.

**Review by kowalczyka — DISMISSED** [review]
:lgtm:

> Reviewed 7 of 8 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-approval/41#-:-MJlsR48CUsPQ8nF2H9d:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by GoebelL — COMMENTED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-approval/41)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
