### PR TITLE
Increase coverage

### PR DESCRIPTION
**Pull request by KabacinskiPiotr**
Create test coverage for connector package

image

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-approval/21)

### CODE REVIEW

**Review by cworf91 — CHANGES_REQUESTED** [review]
> Reviewed 23 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-approval/21)* status: all files reviewed, 24 unresolved discussions (waiting on @KabacinskiPiotr)

___
*[connector/src/main/java/org/oscm/app/connector/activity/LDAPReader.java, line 175 at r1](https://reviewable.io/reviews/servicecatalog/oscm-approval/21#-MFeuHXA135tOlLj8rTB:-MFeuHXA135tOlLj8rTC:b-196bt) ([raw file](https://github.com/servicecatalog/oscm-approval/blob/adeb1c104176a9f2757eb9d257c1d7b7a56372d2/connector/src/main/java/org/oscm/app/connector/activity/LDAPReader.java#L175)):*
> ```Java
>     }
> 
>     protected boolean isHasMore(Map<String, String> transmitData, NamingEnumeration<SearchResult> resultEnumeration) throws javax.naming.NamingException {
> ```

confusing method name. 
___
*[connector/src/test/java/org/oscm/app/connector/activity/DatabaseReaderTest.java, line 85 at r1](https://reviewable.io/reviews/servicecatalog/oscm-approval/21#-MFexfdE7_MHPHGBOUd6:-MFexfdE7_MHPHGBOUd7:bktieuy) ([raw file](https://github.com/servicecatalog/oscm-approval/blob/adeb1c104176a9f2757eb9d257c1d7b7a56372d2/connector/src/test/java/org/oscm/app/connector/activity/DatabaseReaderTest.java#L85)):*
> ```Java
>   public void testDoConfigure() throws ProcessException {
> 
>     when(this.props.containsKey(any())).thenReturn(true);
> ```

Is there a reason to use this keyword all the time? I guess you can remove this in your test classes. 
___
*[connector/src/test/java/org/oscm/app/connector/activity/DatabaseWriterTest.java, line 85 at r1](https://reviewable.io/reviews/servicecatalog/oscm-approval/21#-MFey2jC0DCJ7l1svimW:-MFey2jC0DCJ7l1svimX:b3othjy) ([raw file](https://github.com/servicecatalog/oscm-approval/blob/adeb1c104176a9f2757eb9d257c1d7b7a56372d2/connector/src/test/java/org/oscm/app/connector/activity/DatabaseWriterTest.java#L85)):*
> ```Java
>   public void testDoConfigure() throws ProcessException {
> 
>     when(this.props.containsKey(any())).thenReturn(true);
> ```

same here. "this" should´t be needed. 
___
*[connector/src/test/java/org/oscm/app/connector/activity/EmailWriterTest.java, line 58 at r1](https://reviewable.io/reviews/servicecatalog/oscm-approval/21#-MFeyGhi19QHSDhd3fKL:-MFeyGhi19QHSDhd3fKM:b82ke2) ([raw file](https://github.com/servicecatalog/oscm-approval/blob/adeb1c104176a9f2757eb9d257c1d7b7a56372d2/connector/src/test/java/org/oscm/app/connector/activity/EmailWriterTest.java#L58)):*
> ```Java
>   private Session session;
>   private Logger logger;
>   private static InitialContext mockCtx;
> ```

better name would be initialContext. MockCtx is quite confusing. 
___
*[connector/src/test/java/org/oscm/app/connector/activity/EmailWriterTest.java, line 85 at r1](https://reviewable.io/reviews/servicecatalog/oscm-approval/21#-MFeyMue77RTZpoXshiz:-MFeyMue77RTZpoXshj-:b-krsq3n) ([raw file](https://github.com/servicecatalog/oscm-approval/blob/adeb1c104176a9f2757eb9d257c1d7b7a56372d2/connector/src/test/java/org/oscm/app/connector/activity/EmailWriterTest.java#L85)):*
> ```Java
> 
>     String url = "url";
>     when(this.props.containsKey(any())).thenReturn(true);
> ```

same. 
___
*[connector/src/test/java/org/oscm/app/connector/activity/GatewayTest.java, line 67 at r1](https://reviewable.io/reviews/servicecatalog/oscm-approval/21#-MFeyh_oCkLwVM-fcUPH:-MFeyh_p85iFdCRJgVLj:b-7jl271) ([raw file](https://github.com/servicecatalog/oscm-approval/blob/adeb1c104176a9f2757eb9d257c1d7b7a56372d2/connector/src/test/java/org/oscm/app/connector/activity/GatewayTest.java#L67)):*
> ```Java
>   public void testDoConfigure() throws ProcessException {
> 
>     this.gateway.doConfigure(this.props);
> ```

same.
___
*[connector/src/test/java/org/oscm/app/connector/activity/HTTPClientTest.java, line 74 at r1](https://reviewable.io/reviews/servicecatalog/oscm-approval/21#-MFezKbq3Tw5xu8OiCHh:-MFezKbq3Tw5xu8OiCHi:b-7jl271) ([raw file](https://github.com/servicecatalog/oscm-approval/blob/adeb1c104176a9f2757eb9d257c1d7b7a56372d2/connector/src/test/java/org/oscm/app/connector/activity/HTTPClientTest.java#L74)):*
> ```Java
>   public void testDoConfigure() throws ProcessException {
> 
>     this.httpClient.doConfigure(this.props);
> ```

same.
___
*[connector/src/test/java/org/oscm/app/connector/activity/LDAPReaderTest.java, line 80 at r1](https://reviewable.io/reviews/servicecatalog/oscm-approval/21#-MFez_DM-vfw6pHwv847:-MFez_DM-vfw6pHwv848:bb7od0r) ([raw file](https://github.com/servicecatalog/oscm-approval/blob/adeb1c104176a9f2757eb9d257c1d7b7a56372d2/connector/src/test/java/org/oscm/app/connector/activity/LDAPReaderTest.java#L80)):*
> ```Java
>   public void testDoConfigure() throws ProcessException {
> 
>     this.ldapReader.doConfigure(this.props);
> ```

same
___
*[connector/src/test/java/org/oscm/app/connector/activity/LDAPReaderTest.java, line 163 at r1](https://reviewable.io/reviews/servicecatalog/oscm-approval/21#-MFezsbj3wUwMBZufedR:-MFezsbk42IG6lNioM5S:b-99cp6u) ([raw file](https://github.com/servicecatalog/oscm-approval/blob/adeb1c104176a9f2757eb9d257c1d7b7a56372d2/connector/src/test/java/org/oscm/app/connector/activity/LDAPReaderTest.java#L163)):*
> ```Java
> 
>   @Test
>   public void testIsHasMoreReturnHasMoreAttr() throws Exception {
> ```

Only camelcase is here hard to understand. Try to split the name like testIsHasMore_ReturnHasMoreAttr().  First part is the method unter test and second part the expected behaviour. This style is also fit the java naming convention for testing. 
___
*[connector/src/test/java/org/oscm/app/connector/activity/LDAPReaderTest.java, line 182 at r1](https://reviewable.io/reviews/servicecatalog/oscm-approval/21#-MFf-WDn0Z6Kq9sAeynh:-MFf-WDn0Z6Kq9sAeyni:bdiaf4t) ([raw file](https://github.com/servicecatalog/oscm-approval/blob/adeb1c104176a9f2757eb9d257c1d7b7a56372d2/connector/src/test/java/org/oscm/app/connector/activity/LDAPReaderTest.java#L182)):*
> ```Java
> 
>   @Test
>   public void testIsReturnAttributeReturnTrue() throws Exception {
> ```

see above. 
___
*[connector/src/test/java/org/oscm/app/connector/activity/LDAPTest.java, line 66 at r1](https://reviewable.io/reviews/servicecatalog/oscm-approval/21#-MFf-hB4EeyTBXo9EsxU:-MFf-hB4EeyTBXo9EsxV:b-7iwvbp) ([raw file](https://github.com/servicecatalog/oscm-approval/blob/adeb1c104176a9f2757eb9d257c1d7b7a56372d2/connector/src/test/java/org/oscm/app/connector/activity/LDAPTest.java#L66)):*
> ```Java
>   public void testLdapConstructor() {
> 
>     String urlLDAP = Whitebox.getInternalState(this.ldapSpy, "directoryURL");
> ```

this.
___
*[connector/src/test/java/org/oscm/app/connector/framework/ActivityTest.java, line 98 at r1](https://reviewable.io/reviews/servicecatalog/oscm-approval/21#-MFf-zQS0yo8SwQ0d-Vf:-MFf-zQS0yo8SwQ0d-Vg:bb7p543) ([raw file](https://github.com/servicecatalog/oscm-approval/blob/adeb1c104176a9f2757eb9d257c1d7b7a56372d2/connector/src/test/java/org/oscm/app/connector/framework/ActivityTest.java#L98)):*
> ```Java
>   @Test(expected = ProcessException.class)
>   public void testReplacePlaceholderTransmitDataWithoutKey() throws Exception {
>     this.transmitData.put("wrongKey", "anyValue");
> ```

this
___
*[connector/src/test/java/org/oscm/app/connector/framework/ProcessExceptionTest.java, line 43 at r1](https://reviewable.io/reviews/servicecatalog/oscm-approval/21#-MFf0CeaCuO64GimmtoA:-MFf0CeaCuO64GimmtoB:bb7p543) ([raw file](https://github.com/servicecatalog/oscm-approval/blob/adeb1c104176a9f2757eb9d257c1d7b7a56372d2/connector/src/test/java/org/oscm/app/connector/framework/ProcessExceptionTest.java#L43)):*
> ```Java
>   @Test
>   public void testProcessException() {
>     this.process = new ProcessException(this.message, this.errorCode, this.cause);
> ```

this
___
*[connector/src/test/java/org/oscm/app/connector/framework/ProcessExceptionTest.java, line 54 at r1](https://reviewable.io/reviews/servicecatalog/oscm-approval/21#-MFf0knQ8NR3Ot5vHhNv:-MFf0knQ8NR3Ot5vHhNw:b-ae0dif) ([raw file](https://github.com/servicecatalog/oscm-approval/blob/adeb1c104176a9f2757eb9d257c1d7b7a56372d2/connector/src/test/java/org/oscm/app/connector/framework/ProcessExceptionTest.java#L54)):*
> ```Java
> 
>   @Test
>   public void testProcessExceptionWithoutException() {
> ```

testProcessException_withoutException()
But does this test make sence?
___
*[connector/src/test/java/org/oscm/app/connector/framework/ProcessTest.java, line 46 at r1](https://reviewable.io/reviews/servicecatalog/oscm-approval/21#-MFf1qrJAlk12mEFbG5P:-MFf1qrJAlk12mEFbG5Q:bb7p543) ([raw file](https://github.com/servicecatalog/oscm-approval/blob/adeb1c104176a9f2757eb9d257c1d7b7a56372d2/connector/src/test/java/org/oscm/app/connector/framework/ProcessTest.java#L46)):*
> ```Java
>   public void testSetConfiguration() {
> 
>     this.process.setConfiguration(this.props);
> ```

this
___
*[connector/src/test/java/org/oscm/app/connector/util/SpringBeanSupportTest.java, line 58 at r1](https://reviewable.io/reviews/servicecatalog/oscm-approval/21#-MFf22T43L2sCXwOxW2H:-MFf22T43L2sCXwOxW2I:bxa607n) ([raw file](https://github.com/servicecatalog/oscm-approval/blob/adeb1c104176a9f2757eb9d257c1d7b7a56372d2/connector/src/test/java/org/oscm/app/connector/util/SpringBeanSupportTest.java#L58)):*
> ```Java
> 
>     @Test
>     public void testGetPropertyWithStringDefaultValueWithKey() {
> ```

testGetProperty_withStringDefaultValue_withKey() 
___
*[connector/src/test/java/org/oscm/app/connector/util/SpringBeanSupportTest.java, line 60 at r1](https://reviewable.io/reviews/servicecatalog/oscm-approval/21#-MFf205yDJiGPL7jnCPH:-MFf205yDJiGPL7jnCPI:bb7p543) ([raw file](https://github.com/servicecatalog/oscm-approval/blob/adeb1c104176a9f2757eb9d257c1d7b7a56372d2/connector/src/test/java/org/oscm/app/connector/util/SpringBeanSupportTest.java#L60)):*
> ```Java
>     public void testGetPropertyWithStringDefaultValueWithKey() {
>       String key = "key";
>       when(this.props.containsKey(anyString())).thenReturn(true);
> ```

this
___
*[connector/src/test/java/org/oscm/app/connector/util/SpringBeanSupportTest.java, line 63 at r1](https://reviewable.io/reviews/servicecatalog/oscm-approval/21#-MFf3abO7xGkOo3tnwCg:-MFf3abO7xGkOo3tnwCh:b-n6kpzi) ([raw file](https://github.com/servicecatalog/oscm-approval/blob/adeb1c104176a9f2757eb9d257c1d7b7a56372d2/connector/src/test/java/org/oscm/app/connector/util/SpringBeanSupportTest.java#L63)):*
> ```Java
>       when(this.props.getProperty(anyString())).thenReturn(key);
> 
>       final String result = SpringBeanSupport.getProperty(this.props, key, anyString());
> ```

I´m not sure if you are using a static code analytic tool which indicates this variable should be final. Anyway, here is no way this String can be overriden. Just as a hint. 
___
*[connector/src/test/java/org/oscm/app/connector/util/SpringBeanSupportTest.java, line 69 at r1](https://reviewable.io/reviews/servicecatalog/oscm-approval/21#-MFf2A29AZzCSPn3gSJL:-MFf2A29AZzCSPn3gSJM:byr4ffv) ([raw file](https://github.com/servicecatalog/oscm-approval/blob/adeb1c104176a9f2757eb9d257c1d7b7a56372d2/connector/src/test/java/org/oscm/app/connector/util/SpringBeanSupportTest.java#L69)):*
> ```Java
> 
>     @Test
>     public void testGetPropertyWithStringDefaultValueWithoutKey() {
> ```

see above
___
*[connector/src/test/java/org/oscm/app/connector/util/SpringBeanSupportTest.java, line 79 at r1](https://reviewable.io/reviews/servicecatalog/oscm-approval/21#-MFf2BeG1ePOqwEfFnfv:-MFf2BeG1ePOqwEfFnfw:byr4ffv) ([raw file](https://github.com/servicecatalog/oscm-approval/blob/adeb1c104176a9f2757eb9d257c1d7b7a56372d2/connector/src/test/java/org/oscm/app/connector/util/SpringBeanSupportTest.java#L79)):*
> ```Java
> 
>     @Test
>     public void testGetPropertyWithBooleanDefaultValueWithKey() {
> ```

see above
___
*[connector/src/test/java/org/oscm/app/connector/util/SpringBeanSupportTest.java, line 90 at r1](https://reviewable.io/reviews/servicecatalog/oscm-approval/21#-MFf2C1I6B75B7-nUtdD:-MFf2C1I6B75B7-nUtdE:byr4ffv) ([raw file](https://github.com/servicecatalog/oscm-approval/blob/adeb1c104176a9f2757eb9d257c1d7b7a56372d2/connector/src/test/java/org/oscm/app/connector/util/SpringBeanSupportTest.java#L90)):*
> ```Java
> 
>     @Test
>     public void testGetPropertyWithBooleanDefaultValueWithoutKey() {
> ```

see above
___
*[connector/src/test/java/org/oscm/app/connector/util/SpringBeanSupportTest.java, line 153 at r1](https://reviewable.io/reviews/servicecatalog/oscm-approval/21#-MFf2jmc8tGZjN7gNSou:-MFf2jmc8tGZjN7gNSov:bqt3i3b) ([raw file](https://github.com/servicecatalog/oscm-approval/blob/adeb1c104176a9f2757eb9d257c1d7b7a56372d2/connector/src/test/java/org/oscm/app/connector/util/SpringBeanSupportTest.java#L153)):*
> ```Java
> 
>     @Test
>     public void testGetPropertyWithIntegerDefaultValueWithKey() {
> ```

testGetProperty_withIntegerDefaultValue_withKey
___
*[connector/src/test/java/org/oscm/app/connector/util/SpringBeanSupportTest.java, line 154 at r1](https://reviewable.io/reviews/servicecatalog/oscm-approval/21#-MFf2tNN9Fc-x80HqxtX:-MFf2tNN9Fc-x80HqxtY:bb7p543) ([raw file](https://github.com/servicecatalog/oscm-approval/blob/adeb1c104176a9f2757eb9d257c1d7b7a56372d2/connector/src/test/java/org/oscm/app/connector/util/SpringBeanSupportTest.java#L154)):*
> ```Java
>     @Test
>     public void testGetPropertyWithIntegerDefaultValueWithKey() {
>       when(this.props.containsKey(anyString())).thenReturn(this.isContain);
> ```

this
___
*[connector/src/test/java/org/oscm/app/connector/util/SpringBeanSupportTest.java, line 163 at r1](https://reviewable.io/reviews/servicecatalog/oscm-approval/21#-MFf2qUb5XZ-1BQetHAY:-MFf2qUb5XZ-1BQetHAZ:bq6y5p) ([raw file](https://github.com/servicecatalog/oscm-approval/blob/adeb1c104176a9f2757eb9d257c1d7b7a56372d2/connector/src/test/java/org/oscm/app/connector/util/SpringBeanSupportTest.java#L163)):*
> ```Java
> 
>     @Test(expected = IllegalArgumentException.class)
>     public void testGetPropertyWhenPropsIsNull() {
> ```

testGetProperty_whenPropsIsNull()

**Review by KabacinskiPiotr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-approval/21)* status: 19 of 23 files reviewed, 24 unresolved discussions (waiting on @cworf91 and @KabacinskiPiotr)

___
*[connector/src/main/java/org/oscm/app/connector/activity/LDAPReader.java, line 175 at r1](https://reviewable.io/reviews/servicecatalog/oscm-approval/21#-MFeuHXA135tOlLj8rTB:-MFiqrQYCKhD_Wt-Iwk8:bb6un1j) ([raw file](https://github.com/servicecatalog/oscm-approval/blob/adeb1c104176a9f2757eb9d257c1d7b7a56372d2/connector/src/main/java/org/oscm/app/connector/activity/LDAPReader.java#L175)):*
<details><summary><i>Previously, cworf91 (cworf91) wrote…</i></summary><blockquote>

confusing method name. 
</blockquote></details>

Done
___
*[connector/src/test/java/org/oscm/app/connector/activity/DatabaseReaderTest.java, line 85 at r1](https://reviewable.io/reviews/servicecatalog/oscm-approval/21#-MFexfdE7_MHPHGBOUd6:-MFik_kF6Jug2z8uXJuE:bx71jab) ([raw file](https://github.com/servicecatalog/oscm-approval/blob/adeb1c104176a9f2757eb9d257c1d7b7a56372d2/connector/src/test/java/org/oscm/app/connector/activity/DatabaseReaderTest.java#L85)):*
<details><summary><i>Previously, cworf91 (cworf91) wrote…</i></summary><blockquote>

Is there a reason to use this keyword all the time? I guess you can remove this in your test classes. 
</blockquote></details>

I think this is a good practice that is used in other big Java projects like Spring Boot, it 
makes code more readable (Easier to distinguish fields from local variables) and it is easier to distinguish standard calls from static calls
___
*[connector/src/test/java/org/oscm/app/connector/activity/EmailWriterTest.java, line 58 at r1](https://reviewable.io/reviews/servicecatalog/oscm-approval/21#-MFeyGhi19QHSDhd3fKL:-MFixJXbEey-ELLcthuG:bb6un1j) ([raw file](https://github.com/servicecatalog/oscm-approval/blob/adeb1c104176a9f2757eb9d257c1d7b7a56372d2/connector/src/test/java/org/oscm/app/connector/activity/EmailWriterTest.java#L58)):*
<details><summary><i>Previously, cworf91 (cworf91) wrote…</i></summary><blockquote>

better name would be initialContext. MockCtx is quite confusing. 
</blockquote></details>

Done
___
*[connector/src/test/java/org/oscm/app/connector/activity/LDAPReaderTest.java, line 163 at r1](https://reviewable.io/reviews/servicecatalog/oscm-approval/21#-MFezsbj3wUwMBZufedR:-MFixNK7Bt8bYq45gBEP:bdenfzn) ([raw file](https://github.com/servicecatalog/oscm-approval/blob/adeb1c104176a9f2757eb9d257c1d7b7a56372d2/connector/src/test/java/org/oscm/app/connector/activity/LDAPReaderTest.java#L163)):*
<details><summary><i>Previously, cworf91 (cworf91) wrote…</i></summary><blockquote>

Only camelcase is here hard to understand. Try to split the name like testIsHasMore_ReturnHasMoreAttr().  First part is the method unter test and second part the expected behaviour. This style is also fit the java naming convention for testing. 
</blockquote></details>

I think it is not a good idea, underscores are not used in R. C. Martin's book and in other Java projects (Spring-Boot)
___
*[connector/src/test/java/org/oscm/app/connector/framework/ProcessExceptionTest.java, line 54 at r1](https://reviewable.io/reviews/servicecatalog/oscm-approval/21#-MFf0knQ8NR3Ot5vHhNv:-MFiqwlGA1i7i_f_E5xr:bjd0il1) ([raw file](https://github.com/servicecatalog/oscm-approval/blob/adeb1c104176a9f2757eb9d257c1d7b7a56372d2/connector/src/test/java/org/oscm/app/connector/framework/ProcessExceptionTest.java#L54)):*
<details><summary><i>Previously, cworf91 (cworf91) wrote…</i></summary><blockquote>

testProcessException_withoutException()
But does this test make sence?
</blockquote></details>

This test calls a constructor that does not specify Exception parameters, I changed the name a bit
___
*[connector/src/test/java/org/oscm/app/connector/util/SpringBeanSupportTest.java, line 63 at r1](https://reviewable.io/reviews/servicecatalog/oscm-approval/21#-MFf3abO7xGkOo3tnwCg:-MFiwtxXAIlci9I28Y1G:b-cmvkr9) ([raw file](https://github.com/servicecatalog/oscm-approval/blob/adeb1c104176a9f2757eb9d257c1d7b7a56372d2/connector/src/test/java/org/oscm/app/connector/util/SpringBeanSupportTest.java#L63)):*
<details><summary><i>Previously, cworf91 (cworf91) wrote…</i></summary><blockquote>

I´m not sure if you are using a static code analytic tool which indicates this variable should be final. Anyway, here is no way this String can be overriden. Just as a hint. 
</blockquote></details>

I used the word final to make the code clearer and more readable

**Review by cworf91 — DISMISSED** [review]
> Reviewed 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-approval/21)* status: 21 of 23 files reviewed, 20 unresolved discussions (waiting on @cworf91 and @KabacinskiPiotr)

___
*[connector/src/test/java/org/oscm/app/connector/activity/DatabaseReaderTest.java, line 85 at r1](https://reviewable.io/reviews/servicecatalog/oscm-approval/21#-MFexfdE7_MHPHGBOUd6:-MFj4mAmAYMhc0E92EVF:b5a0238) ([raw file](https://github.com/servicecatalog/oscm-approval/blob/adeb1c104176a9f2757eb9d257c1d7b7a56372d2/connector/src/test/java/org/oscm/app/connector/activity/DatabaseReaderTest.java#L85)):*
<details><summary><i>Previously, KabacinskiPiotr wrote…</i></summary><blockquote>

I think this is a good practice that is used in other big Java projects like Spring Boot, it 
makes code more readable (Easier to distinguish fields from local variables) and it is easier to distinguish standard calls from static calls
</blockquote></details>

Regarding documentation: 
https://docs.oracle.com/javase/tutorial/java/javaOO/thiskey.html
this should just be used when it shadows an other variable. 

Nevertheless, I guess that is not a good pracice at all. It just causes unused code.
Check: 
https://stackoverflow.com/questions/2411270/when-should-i-use-this-in-a-class
___
*[connector/src/test/java/org/oscm/app/connector/activity/LDAPReaderTest.java, line 163 at r1](https://reviewable.io/reviews/servicecatalog/oscm-approval/21#-MFezsbj3wUwMBZufedR:-MFj30zV16KGZFWWjyMv:b-hlax9r) ([raw file](https://github.com/servicecatalog/oscm-approval/blob/adeb1c104176a9f2757eb9d257c1d7b7a56372d2/connector/src/test/java/org/oscm/app/connector/activity/LDAPReaderTest.java#L163)):*
<details><summary><i>Previously, KabacinskiPiotr wrote…</i></summary><blockquote>

I think it is not a good idea, underscores are not used in R. C. Martin's book and in other Java projects (Spring-Boot)
</blockquote></details>

In clean code, robert martin follows a approch where you have very small classes, methods and less responability of each. Unfortunately we don´t have this stile of code. Other authors like Roy Osherove  suggest to use underscores to increase the readability of the code.

**Review by GoebelL — APPROVED** [review]
> Reviewed 8 of 23 files at r1, 1 of 4 files at r2, 14 of 14 files at r3, 9 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-approval/21)* status: all files reviewed, 20 unresolved discussions (waiting on @KabacinskiPiotr)

**Pull request merged**
