### PR TITLE
Task/authentication

### PR DESCRIPTION
**Pull request by kowalczyka**
**Changes in this Pull Request:**
- Modified authentication process

**Mandatory checks:**
- [x] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [x] Changes were tested manually
- [ ] Java code changes are unit tested

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 

**To be checked by the pull request owner:**
- [ ] .MASTER/job/BES_MASTER_IT/
- [ ] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_WS_Tests_OIDC/
- [ ] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
- OSCM_Docker_Build_and_push #268

**Screenshot (if applicable):**
- N/A

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-approval/40)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> Reviewed 10 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-approval/40)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @GoebelL and @kowalczyka)

___
*[approval-impl/src/main/java/org/oscm/app/approval/servlet/LoginServlet.java, line 66 at r2](https://reviewable.io/reviews/servicecatalog/oscm-approval/40#-MJ68cD-BJ3_6nF8bXUp:-MJ68cD0A-UgSSFAJiIb:b-wqjnej) ([raw file](https://github.com/servicecatalog/oscm-approval/blob/94825cc3db9daadb807c38bee66f65f0e5b70645/approval-impl/src/main/java/org/oscm/app/approval/servlet/LoginServlet.java#L66)):*
> ```Java
>       return;
>     } catch (Exception e) {
>       LOGGER.error(e.getMessage());
> ```

Catch and log generic exceptions? What happens if authentication fails? Is this handling missing?

**Review by GoebelL — COMMENTED** [review]
> Reviewed 1 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-approval/40)* status: all files reviewed, 1 unresolved discussion (waiting on @kowalczyka)

**Review by kowalczyka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-approval/40)* status: 8 of 12 files reviewed, 1 unresolved discussion (waiting on @GoebelL)

___
*[approval-impl/src/main/java/org/oscm/app/approval/servlet/LoginServlet.java, line 66 at r2](https://reviewable.io/reviews/servicecatalog/oscm-approval/40#-MJ68cD-BJ3_6nF8bXUp:-MJ6cl3dDG8vu5k4sdAk:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-approval/blob/94825cc3db9daadb807c38bee66f65f0e5b70645/approval-impl/src/main/java/org/oscm/app/approval/servlet/LoginServlet.java#L66)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Catch and log generic exceptions? What happens if authentication fails? Is this handling missing?
</blockquote></details>

Done.

**Review by GoebelL — APPROVED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-approval/40)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
